version: "3"
services:
  api:
    image: awabeltigani/fastapi
    depends_on:
      - postgres #will tell docker I want you to start the postgres cntauiner before the api one
    ports:
      - 80:8000
    volumes:
      - ./:/usr/src/app:ro
#    command: uvicorn FastAPI90.main:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME={DATABASE_NAME}
      - DATABASE_USERNAME={DATABASE_USERNAME}
      - SECRET_KEY={SECRET_KEY}
      - ALGORITHM={ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES={ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD={DATABASE_PASSWORD}
      - POSTGRES_DB={DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
