version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres #will tell docker I want you to start the postgres cntauiner before the api one
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn FastAPI90.main:app --host 0.0.0.0 --port 800 --reload
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=PASSWORD**hIDDEN
      - DATABASE_NAME=FastAPI
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=SECRETkey_HIDDEN
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Arsenalforever10%26
      - POSTGRES_DB=FastAPI
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
