"""add phone_num to users

Revision ID: daf7f3e51d13
Revises: 1a61808bdaa1
Create Date: 2025-07-20 05:54:29.205331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf7f3e51d13'
down_revision: Union[str, Sequence[str], None] = '1a61808bdaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_num', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_num')
    # ### end Alembic commands ###
